name       : npth
version    : 1.4
release    : 2
source     :
    - ftp://ftp.gnupg.org/gcrypt/npth/npth-1.4.tar.bz2 : 8915141836a3169a502d65c1ebd785fcc6d406cae5ee84474272ebf2fa96f1f2
license    :
    - GPL-2.0
    - LPL-3.0
component  : programming.library
summary    : Non-preemptive threads implementation (GNU pth)
patterns   :
    - devel: /usr/bin
emul32     : yes
description: |
    nPth is a library to provide the GNU Pth API and thus a non-preemptive threads implementation.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
