name       : npth
version    : '1.5'
release    : 3
source     :
    - ftp://ftp.gnupg.org/gcrypt/npth/npth-1.5.tar.bz2 : 294a690c1f537b92ed829d867bee537e46be93fbd60b16c04630fbbfcd9db3c2
license    :
    - LGPL-2.1
component  : programming.library
summary    : Non-preemptive threads implementation (GNU pth)
patterns   :
    - devel : /usr/bin
emul32     : yes
description: |
    nPth is a library to provide the GNU Pth API and thus a non-preemptive threads implementation.
setup      : |
    %configure --disable-static --prefix=/usr
build      : |
    %make
install    : |
    %make_install
