name       : npth
version    : '1.6'
release    : 4
source     :
    - https://gnupg.org/ftp/gcrypt/npth/npth-1.6.tar.bz2 : 1393abd9adcf0762d34798dc34fdcf4d0d22a8410721e76f1e3afcd1daa4e2d1
license    : LGPL-2.1-or-later
summary    : Non-preemptive threads implementation (GNU pth)
component  : programming.library
description: |
    nPth is a library to provide the GNU Pth API and thus a non-preemptive threads implementation.
patterns   :
    - devel : /usr/bin
emul32     : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
